name: Upload

# Only trigger, when the "Tests" workflow succeeds
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Install Twine
      - name: Install Twine dependencies
        run: |
          pip install setuptools wheel twine

      # Build and publish distribution to TestPyPi
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
        run: |
          python setup.py sdist
          twine upload --skip-existing dist/graph-tiger-*.tar.gz
